### ISSUE TITLE
lsp-set-addresses parsing bug

### ISSUE THREAD

**Issue by ryzhyk** [ryzhyk/cocoon2#9]
This happens in test 2319:

error parsing:  --timeout=30 lsp-set-addresses lp2 'f0:00:00:00:00:2 192.168.0.2' Error at position 1,37 => "sses lp2 '*f0:00:00:0". Expected: EthAddress

**Comment by mihaibudiu** [comment]
The ehternet address in the line you sent is malformed; the last number has only 1 hex digit.
I don't see this in the test example.

**Comment by ryzhyk** [comment]
True. I will submit an OVS bug report.
